name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tomasliumparas/container-jenkins-slave-python
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        registry: docker.pkg.github.com
        workidr: "3.6"
