name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push to GitHub Package
      uses: opspresso/action-docker@v0.2.1
      env:
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        REGISTRY: "docker.pkg.github.com"
        BUILD_PATH: "3.6"
        IMAGE_NAME: "tomasliumparas/jenkins-slave-python"
        TAG_NAME: "v0.0.1"
        LATEST: "true"
